import { styled } from "@mui/system";

export const Container = styled("div")(({theme})=>({
  background:"#3b3d43",
  button:{
    border:0,
    padding:0,
    fontFamily:"Poppins",
    background:"transparent",
    color:"#3b3d43",
    cursor:"pointer",
    ":hover":{
      color:"rgba(255, 255, 255, 0.75)",
    },
  },
  ".navbar":{
    [theme.breakpoints.down(600)]: {
      justifyContent:"space-between",
      padding:"0 0 0 16px",
    },
    position:"fixed",
    zIndex:"1",
    top:0,
    left:0,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    width:"100%",
    height:"64px",
    background:"#19191c",
    color:"#f9f9f9",
    fontFamily:"Poppins"
  },
  ".navbar-overlay":{
    [theme.breakpoints.down(600)]: {
      display:"none",
    },
    position:"fixed",
    zIndex:"2",
    top:0,
    left:0,
    width:"100%",
    height:"100%",
    background:"rgba(0, 0, 0, 0.5)",
    visibility:"hidden",
    opacity:0,
    transition:"0.5s",
  },
  ".navbar-overlayOpen":{
    position:"fixed",
    zIndex:"2",
    top:0,
    left:0,
    width:"100%",
    height:"100%",
    background:"rgba(0, 0, 0, 0.5)",
    visibility:"visible",
    opacity:1,
    transition:"0.5s",
  },
  ".navbar-burger":{
    [theme.breakpoints.down(600)]: {
      display:"none",
    },
    position: "absolute",
    top:0,
    left:0,
    display:"grid",
    placeItems:"center",
    width:"64px",
    height:"64px",
    padding:0,
  },
  ".navbar-title":{
    margin:0,
    fontSize:"16px",
  },
  ".navbar-menu":{
    [theme.breakpoints.down(600)]: {
      alignItems:"center",
      position: "static",
      width:"auto",
      translate:"0 0",
      background:"transparent",
      visibility:"visible",
      flexDirection:"row",
    },
    position:"fixed",
    zIndex:"3",
    top:0,
    left:0,
    translate:"-100% 0",
    width:"270px",
    height:"100%",
    display:"flex",
    padding:"20px",
    gap:"8px",
    flexDirection:"column",
    alignItems:"flex-start",
    background:"#000",
    visibility:"hidden",
    transition:"all 0.3s",
    button:{
      color:"rgba(255, 255,255,0.5)",
      background:"transparent",
      padding:"0 8px",
      transition:"all 0.3s",
    },
  },
  ".navbar-menuOpen":{
    a:{
      textDecoration:"none",
      color:"inherit",
      background:"transparent",
      transition:"all 0.3s",
      ":hover":{
        color:"inherit",
      },
    },
    position:"fixed",
    padding:"20px",
    zIndex:"3",
    top:0,
    left:0,
    translate:"0 0",
    width:"270px",
    height:"100%",
    display:"flex",
    gap:"8px",
    flexDirection:"column",
    background:"#000",
    visibility:"visible",
    transition:"all 0.3s",
    alignItems:"flex-start",
  },
  ".active":{
    color:"inherit",
  },
}));