import { styled } from "@mui/system";

export const Container = styled("div")({
  margin:0,
  padding:0,
  height:"100vh",
  backgroundColor:"#f1f1f1",
  display:"flex",
  fontFamily:"sans-serif",
  minHeight:"100%",
  alignItems:"center",
  justifyContent:"center",
  ".container":{
    margin:"0 auto",
    maxWidth:"34rem",
    width:"90%",
  },
  input:{
    backgroundColor:"transparent",
    border:"none",
    color:"#fff",
    font:"inherit",
    width:"auto",
    ":hover":{
      color:"#fff",
    },
  },
  label:{
    display:"block",
  },
  ".card":{
    backgroundColor:"#171a1c",
    borderRadius:"14px",
    color:"#bebebe",
    padding:"32px",
  },
  ".header":{
    marginBottom:"7rem",
  },
  ".title":{
    color:"#fff",
    float:"left",
    fontSize:"1.5rem",
  },
  ".logo":{
    float:"right",
  },
  ".row":{
    marginBottom:"1.5rem",
  },
  ".content":{
    marginBottom:"5rem",
    input:{
      outline:"none",
    },
  },
  ".card-number":{
    fontSize:"32px",
  },
  ".card-expire":{
    float:"left",
    input:{
      fontSize:"0.9rem",
    },
  },
  ".card-expire-month":{
    width:"22%",
    float:"left",
  },
  ".card-expire-year":{
    float:"left",
  },
  ".card-cvv":{
    float:"right",
    input:{
      width:"2rem",
      textAlign:"center",
      fontSize:"0.9rem",
    }
  },

});